eureka:
  client:
    fetch-registry: true
    instance:
      hostname: localhost
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
server:
  port: 8002
spring:
  application:
    name: FAMILY-SERVICE
